version: '3.3'
services:
    flask:
        container_name: flask
        ports:
            - '8001:80'
        image: pse-flask

    db:
        image: pse-mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - '3306:3306'
        container_name: "mysql"
    phpmyadmin:
        image: phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80
    redis:
        image: redis
