version: '3.3'
services:
    flask:
        container_name: flask
        ports:
            - '8001:80'
        image: pse-flask

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - '3306:3306'
        container_name: "mysql"