version: '3.3'
services:
    flask:
        container_name: flask
        restart: on-failure
        depends_on:
            - db
        ports:
            - '${SERVER_PORT}:80'
        image: pse-flask
        volumes:
            - "./app:/app:z"
            - "./emcc_cache:/emcc_cache:z"
        environment:
            SERVER_IP: '${SERVER_IP}'
            EM_CACHE: '${EM_CACHE}'
            MYSQL_USERNAME: '${MYSQL_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_HOST: '${MYSQL_HOST}'
            MYSQL_PORT: '${MYSQL_PORT}'
            MYSQL_DB_NAME: '${MYSQL_DB_NAME}'
    db:
        image: pse-mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: '${MYSQL_ROOT_HOST}'  # needs to be enclosed with quotes
        ports:
            - '${MYSQL_PORT}:3306'
        container_name: "mysql"
    phpmyadmin:
        image: phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: '${PMA_HOST}'
            PMA_PORT: '${PMA_PORT}'
            PMA_ARBITRARY: '${PMA_ARBITRARY}'
        restart: always
        ports:
            - '${PHP_MY_ADMIN_PORT}:80'
    redis:
        image: redis
        ports:
            - 6379:6379
